[package]
name = "cmk"
version = "0.1.0"
authors = ["Vzaa <Vzaa@users.noreply.github.com>"]
edition = "2018"

[dependencies]
curl = "0.4"
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clap = "2.33"
prettytable-rs = "0.8"
